sudo: required
dist: trusty

language: c

# download and install our required cross compilers
install:
  # Make sure we can install i386 packages as some adtools binaries
  # requires i386 libraries being installed to work in the 64bit env
  # of Travis
  - sudo dpkg --add-architecture i386
  - sudo apt-get -qq update || true
  - sudo apt-get -qq install libc6:i386
  # Install all adtools related stuff we need
  - curl -L https://www.amigasoft.net/downloads/adtools-utils.tgz | sudo tar -xvf 
  - if [[ ${BUILD} =~ os4|release ]]; then curl -L https://www.amigasoft.net/downloads/adtools-ppc-amigaos.tgz | sudo | tar -xvf ; fi

# set the PATH variable to the directories the cross compilers are installed.
before_script:
  - export PATH=/opt/ppc-amigaos/bin:${PATH}

# specify a list of variables to test (here we test the build for our supported
# list of operating systems).
env:
  - BUILD="-f GNUMakefile.os4 OS=os4"

# the build command to execute for each test
script:
  - make -C library -j1 ${BUILD}
