name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: amigadev/crosstools:ppc-amigaos

    steps:
    - uses: actions/checkout@v3
    - name: make
      run: make -f GNUMakefile.os4 -j12
    
