name: CI
on:
  push:
    branches: [master]
  pull_request:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    timeout-minutes: 480

    strategy:
      fail-fast: false
      matrix:
        platform: [os4]

    steps:
      - uses: actions/checkout@v2

      - name: setup dependencies
        run: |
          sudo dpkg --add-architecture i386
          sudo apt-get update -y -qq || true
          sudo apt-get -qq install libc6:i386
          sudo ln -s /usr/lib/x86_64-linux-gnu/libmpfr.so.6 /usr/lib/x86_64-linux-gnu/libmpfr.so.4
      - name: setup env
        run : |
          echo "GITHUB_SHA7=$(echo ${GITHUB_SHA::7})" >>$GITHUB_ENV
      - name: install adtools build env
        run: |
          DOWNLOAD_PATH=https://github.com/adtools/adtools/releases/download/20170213
          curl -L ${DOWNLOAD_PATH}/adtools-utils.tar.bz2 | sudo tar xj -C /
          if [[ ${{ matrix.platform }} =~ os4 ]]; then curl -L ${DOWNLOAD_PATH}/adtools-ppc-amigaos.tar.bz2 | sudo tar xj -C / ; fi
      - name: cleanup old action artifacts
        run: .github/workflows/purge_artifacts.sh ${{ secrets.GITHUB_TOKEN }}

      #- name: remote debug tmate session
      #  uses: mxschmitt/action-tmate@v1
      #  if: matrix.platform == 'os4'

      - name: build [${{ matrix.platform }}]
        timeout-minutes: 480
        run: |
          export PATH=/usr/local/amiga/bin:${PATH}
          if [[ ${{ matrix.platform }} =~ os4 ]]; then make -C library -j1 -f GNUmakefile.os4 OS=os4 SHARED=no ; fi
